services:
  database:
    image: postgres:18
    ports:
      - "5433:5432"
    volumes:
      - robot_postgres_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  
  robot:
    container_name: cmp9134_2526_robot
    image: ghcr.io/francescodelduchetto/cmp9134_2526_robotsim:latest
    ports:
      - "5555:5000"
    
volumes:
  robot_postgres_database:

